POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name":"Dieguin",
    "email":"dieguinMaluco@gmail.com"
}

###

GET http://localhost:3333/invites/aa99a803-2336-4882-8b3b-ffab109d7aa0

###

GET http://localhost:3333/subscribers/aa99a803-2336-4882-8b3b-ffab109d7aa0/ranking/clicks

###

POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name":"Usuario indicado",
    "email":"IndicadoUsuario@gmail.com",
    "referrer":"aa99a803-2336-4882-8b3b-ffab109d7aa0" 
}

###

GET http://localhost:3333/subscribers/aa99a803-2336-4882-8b3b-ffab109d7aa0/ranking/count

###

GET http://localhost:3333/subscribers/aa99a803-2336-4882-8b3b-ffab109d7aa0/ranking/count

###

GET http://localhost:3333/ranking

###

GET http://localhost:3333/login/IndicadoUsuario@gmail.com